ALTER TABLE `device_info`
ADD COLUMN `DEPART_ID`  varchar(36) NULL COMMENT '部门ID' AFTER `UPDATETIME`,
ADD COLUMN `CRT_USER_ID`  varchar(36) NULL COMMENT '用户ID' AFTER `DEPART_ID`;

ALTER TABLE `report_info`
ADD COLUMN `DEPART_ID`  varchar(36) NULL COMMENT '部门ID' AFTER `UPDATETIME`,
ADD COLUMN `CRT_USER_ID`  varchar(36) NULL COMMENT '用户ID' AFTER `DEPART_ID`;

ALTER TABLE `command_send_log`
ADD COLUMN `DEPART_ID`  varchar(36) NULL COMMENT '部门ID' AFTER `UPDATETIME`,
ADD COLUMN `CRT_USER_ID`  varchar(36) NULL COMMENT '用户ID' AFTER `DEPART_ID`;

