CREATE TABLE `user_info` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '用户ID，表主键',
  `USERNAME` varchar(40) NOT NULL COMMENT '用户名',
  `PASSWORD` varchar(40) NOT NULL COMMENT '密码',
  `MOBILE` varchar(20) DEFAULT NULL COMMENT '手机号',
  `EMAIL` varchar(40) NOT NULL COMMENT '邮箱',
  `REALNAME` varchar(40) NOT NULL COMMENT '真实姓名',
  `CREATETIME` datetime NOT NULL COMMENT '创建时间',
  `UPDATETIME` datetime DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (`ID`),
  UNIQUE KEY `USER_NAME_IDX` (`USERNAME`) USING BTREE,
  UNIQUE KEY `USER_REAL_NAME_IDX` (`REALNAME`) USING BTREE,
  UNIQUE KEY `USER_MOBILE_IDX` (`MOBILE`) USING BTREE,
  KEY `USER_CREATETIME_IDX` (`CREATETIME`) USING BTREE,
  KEY `USER_UPDATETIME_IDX` (`UPDATETIME`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COMMENT='用户信息表';

insert into user_info(USERNAME,PASSWORD,MOBILE,EMAIL,REALNAME,CREATETIME,UPDATETIME)
VALUES('admin','Aa123456','13998184711','13998184711@139.com','沈阳大学',now(),now());
insert into user_info(USERNAME,PASSWORD,MOBILE,EMAIL,REALNAME,CREATETIME,UPDATETIME)
VALUES('xhjyey','Aa123456','13889333483','13889333483@139.com','小哈津幼儿园',now(),now());

ALTER TABLE `device_info`
ADD COLUMN `USER_ID`  bigint(20) NULL AFTER `UPDATETIME`;

UPDATE device_info set USER_ID = 1;