CREATE TABLE `c_user_info` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '用户ID，表主键',
  `USERNAME` varchar(40) NOT NULL COMMENT '用户名',
  `PASSWORD` varchar(40) NOT NULL COMMENT '密码',
  `MOBILE` varchar(20) DEFAULT NULL COMMENT '手机号',
  `EMAIL` varchar(40) DEFAULT NULL COMMENT '邮箱',
  `WEIXIN` varchar(40) DEFAULT NULL COMMENT '微信号',
  `QQ` varchar(40) DEFAULT NULL COMMENT 'QQ号',
  `CREATETIME` datetime NOT NULL COMMENT '创建时间',
  `UPDATETIME` datetime DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (`ID`),
  UNIQUE KEY `USER_NAME_IDX` (`USERNAME`) USING BTREE,
  KEY `USER_CREATETIME_IDX` (`CREATETIME`) USING BTREE,
  KEY `USER_UPDATETIME_IDX` (`UPDATETIME`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COMMENT='C端用户信息表';

CREATE TABLE `c_user_device_mapping` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'ID，表主键',
  `USER_ID` bigint(20) NOT NULL COMMENT '用户ID',
  `DEVICE_ID` bigint(20) NOT NULL COMMENT '设备ID',
  `DEVICE_DESC` varchar(40) DEFAULT NULL COMMENT '设备描述',
  `IS_DEFAULT` int(1) NOT NULL DEFAULT '0' COMMENT '是否为默认设备 0:不是 1:是',
  PRIMARY KEY (`ID`),
  UNIQUE KEY `USER_DEVICE_MAPPING_IDX` (`USER_ID`,`DEVICE_ID`) USING HASH
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='C端用户与设备关联表';